// This file is auto-generated by `npx convex dev`.
// Do not edit manually. Run `npx convex dev` to regenerate.
//
// Stub for build-time compatibility — will be replaced by actual generated types
// after running `npx convex dev` with a valid Convex deployment.

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
