// This file is auto-generated by `npx convex dev`.
// Do not edit manually. Run `npx convex dev` to regenerate.
//
// Stub for build-time compatibility.
// Will be replaced by actual generated types after running `npx convex dev`.

import type { DataModelFromSchemaDefinition } from "convex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
