// This file is auto-generated by `npx convex dev`.
// Do not edit manually. Run `npx convex dev` to regenerate.
//
// Stub for build-time compatibility.
// Will be replaced by actual generated types after running `npx convex dev`.

export {
  actionGeneric as action,
  internalActionGeneric as internalAction,
  internalMutationGeneric as internalMutation,
  internalQueryGeneric as internalQuery,
  mutationGeneric as mutation,
  queryGeneric as query,
} from "convex/server";
